import { createRouter, Router } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen' // auto-generated by TanStack Router's file-based routing

export const router = createRouter({ routeTree })
