spring.application.name=tasktrading212

BINANCE_API_KEY=anSiCFRs9OLwFKTcEoLZnJ5WdZrMbMt3CUd5lVJ0vmsOEeyMiZLbJnzgo4aoCo0B
BINANCE_SECRET_KEY=MoCQ5a8IHU91ZFcBh3RClqG25agi2AT16BwDjbi9OV7YPui5YG23bIv2YbvedvqF

# Moving Average Strategy Configuration
trading.ma.short-period=5
trading.ma.long-period=20

# Price sampling interval (seconds) for live trading
trading.sample-interval-seconds=3

# Mean Reversion Strategy Configuration
trading.mr.period=20
trading.mr.buy-threshold=0.03
trading.mr.sell-threshold=0.05

# Backtest Configuration
backtest.default-limit=1000

binance_api_url=https://api.binance.com/api/v3/klines

# Logging
logging.level.org.example.tasktrading212.strategy=DEBUG
logging.level.org.example.tasktrading212.service=DEBUG

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/trading212database
spring.datasource.username=postgres
spring.datasource.password=740420

jwt_secret=aDi3MHHf0vHTX8zNBuyAuP27uEnCwQ0OzeVxpt6ZMXR