spring.application.name=tasktrading212

BINANCE_API_KEY=anSiCFRs9OLwFKTcEoLZnJ5WdZrMbMt3CUd5lVJ0vmsOEeyMiZLbJnzgo4aoCo0B
BINANCE_SECRET_KEY=MoCQ5a8IHU91ZFcBh3RClqG25agi2AT16BwDjbi9OV7YPui5YG23bIv2YbvedvqF

# Trading Bot Configuration
trading.buy-drop-percent=0.02
trading.sell-gain-percent=0.05
trading.stop-loss-percent=0.06

# Logging
logging.level.org.example.tasktrading212.strategy=DEBUG
logging.level.org.example.tasktrading212.service=DEBUG

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/trading212database
spring.datasource.username=postgres
spring.datasource.password=740420

jwt_secret=aDi3MHHf0vHTX8zNBuyAuP27uEnCwQ0OzeVxpt6ZMXR